"%dev":
  quarkus:
    datasource:
      db-kind: h2
      username: root
      password: root_password
      jdbc:
        url: jdbc:h2:tcp://localhost/~/test, jdbc:h2:mem:myDB
        max-size: 16

"%prod":
  quarkus:
    datasource:
      db-kind: mariadb
      jdbc:
        url: jdbc:mariadb://${db_name}:3306/authentikey
      username: root
      password: root_password

