name: Java CI

on:
  push:
    branches:
      - main

jobs:

  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: rosariop
          password: ${{ secrets.authentikey_token }}

  build:
    needs: login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - name: Build with Maven
        run: mvn package -Pnative
      - name: Build with Docker
        run: docker build -f src/main/docker/Dockerfile.native -t quarkus/backend:latest .
      - name: Push to Github Packages
        run: |
          docker login ghcr.io --username rosariop --password ${{ secrets.authentikey_token }}
          docker tag quarkus/backend:latest ghcr.io/authentikey/authentikey/authentikey:stable
          docker push ghcr.io/authentikey/authentikey/authentikey:stable
